# Generated by Django 3.0.8 on 2020-09-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20200808_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grades_test_option',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
