# Generated by Django 3.0.8 on 2020-09-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_user_grades_test_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grades_test_option',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
