# Generated by Django 3.0.8 on 2020-10-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20200927_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grades_test_option',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
