# Generated by Django 3.0.8 on 2020-10-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20201009_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grades_test_option',
            field=models.CharField(default='', max_length=100),
        ),
    ]
