# Generated by Django 3.0.8 on 2020-10-09 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20201009_1646'),
        ('mainsite', '0006_auto_20201009_1955'),
    ]

    operations = [
    ]
