# Generated by Django 3.0.8 on 2020-10-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_merge_20201009_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grades_test_option',
            field=models.CharField(default=[], max_length=100),
        ),
    ]
