# Generated by Django 3.0.8 on 2020-10-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_auto_20201009_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quiz_option',
            field=models.IntegerField(default=50),
        ),
    ]
