# Generated by Django 3.0.8 on 2020-10-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_user_quiz_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='quiz_option',
            field=models.CharField(default=50, max_length=255),
        ),
    ]
