# Generated by Django 3.0.8 on 2020-09-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('clock', models.IntegerField()),
                ('status', models.TextField(choices=[('1', 'Done'), ('2', '1/3 left'), ('3', 'Just started'), ('4', 'Failed')])),
            ],
        ),
    ]
