# Generated by Django 3.0.8 on 2020-09-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeekSchedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='clock',
            field=models.IntegerField(null=True),
        ),
    ]
