# Generated by Django 3.0.8 on 2020-09-29 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeekSchedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
