# Generated by Django 3.0.8 on 2020-09-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeekSchedule', '0002_auto_20200912_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='clock',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
    ]
