# Generated by Django 3.0.8 on 2020-10-05 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizBank', '0002_auto_20201002_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='question',
            new_name='question1',
        ),
    ]
