# Generated by Django 3.0.8 on 2020-10-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizBank', '0003_auto_20201005_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='image2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='image3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
