# Generated by Django 3.0.8 on 2020-10-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizBank', '0004_auto_20201005_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='year',
            field=models.TextField(blank=True, null=True),
        ),
    ]
