# Generated by Django 3.0.8 on 2020-10-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizBank', '0005_auto_20201010_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
