# Generated by Django 3.0.8 on 2020-09-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('test', models.CharField(default=0, max_length=100)),
                ('scope', models.CharField(default=0, max_length=100)),
                ('grade', models.TextField(blank=True)),
                ('subject', models.IntegerField(default=0)),
            ],
        ),
    ]
