# Generated by Django 3.0.8 on 2020-10-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0002_link_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='user',
        ),
    ]
