# Generated by Django 3.0.8 on 2020-10-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0003_remove_link_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='subject',
            field=models.IntegerField(default={}),
        ),
    ]
